data_dir: '/home/fortson/manth145/data/BraTS2021_Seg/ALL/ASNR-MICCAI-BraTS2023-ALL-Challenge-TrainingData/'
ckpt_folder: './checkpoints'
run_name: 'ALL_BCE_2.3M'
batch_size: 2
start_from_last: True
generator_transfer_learn_checkpoint: ''
discriminator_transfer_learn_checkpoint: ''
generator_learning_rate: 0.0001
discriminator_learning_rate: 0.0001
n_epochs: 60
normalize: True
add_noise: True